jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install poetry poe

      - name: Build package
        run: |
          cd src
          poe build-dist
        env:
          build_secret: ${{ secrets.BUILD_SECRET }}
