name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write  # Necessary to create releases and upload assets

jobs:
  build-and-release:
    name: Build and Release Package
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      # Install Poetry and Poethepoet
      - name: Install Poetry and Tools
        run: |
          pipx install "poetry>=1.7.0"
          pipx install poethepoet

      # adds pipx binaries to PATH
      - name: Ensure pipx binaries are in PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH


      # Install dependencies and prepare the environment
      - name: Install Dependencies
        run: |
          poetry install

      #verify installation of pipx and poetry
      - name: Verify pipx and poetry installation
        run: |
          pipx --version
          poetry --version

      # Build the package
      - name: Build MSI Package
        run: |
          poe build-dist
        env:
          BUILD_SECRET: ${{ secrets.BUILD_SECRET }}

      # Publish the release to GitHub
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src/dist/matt-fishbot-*.msi
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
