name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write # Necessary to create releases and upload assets

jobs:
  build-and-release:
    name: Build and Release Package
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
      - name: Install Poetry
        run: |
          pipx install "poetry>=1.7.0"
          pipx install poethepoet

      - name: Set up Python
        id: pysetup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install package and dependencies
        run: |
          cd src
          poetry env use '${{ steps.pysetup.outputs.python-path }}'
          poetry install

      - name: Build package
        run: |
          cd src
          poe build-dist -v ${{github.ref_name}}
        env:
          BUILD_SECRET: ${{ secrets.BUILD_SECRET }}

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        id: release
        with:
          prerelease: ${{startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'rc')}}
          generate_release_notes: true
          files: |
            ./src/dist/*.msi
